/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	datarepository "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	AdminApiService := datarepository.NewAdminApiService()
	AdminApiController := datarepository.NewAdminApiController(AdminApiService)

	BandwidthApiService := datarepository.NewBandwidthApiService()
	BandwidthApiController := datarepository.NewBandwidthApiController(BandwidthApiService)

	LocationApiService := datarepository.NewLocationApiService()
	LocationApiController := datarepository.NewLocationApiController(LocationApiService)

	SubscriberApiService := datarepository.NewSubscriberApiService()
	SubscriberApiController := datarepository.NewSubscriberApiController(SubscriberApiService)

	router := datarepository.NewRouter(AdminApiController, BandwidthApiController, LocationApiController, SubscriberApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
