/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"encoding/json"
	"net/http"
	"strings"

	//"github.com/gorilla/mux"
)

// BandwidthApiController binds http requests to an api service and writes the service results to the http response
type BandwidthApiController struct {
	service BandwidthApiServicer
	errorHandler ErrorHandler
}

// BandwidthApiOption for how the controller is set up.
type BandwidthApiOption func(*BandwidthApiController)

// WithBandwidthApiErrorHandler inject ErrorHandler into controller
func WithBandwidthApiErrorHandler(h ErrorHandler) BandwidthApiOption {
	return func(c *BandwidthApiController) {
		c.errorHandler = h
	}
}

// NewBandwidthApiController creates a default api controller
func NewBandwidthApiController(s BandwidthApiServicer, opts ...BandwidthApiOption) Router {
	controller := &BandwidthApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all of the api route for the BandwidthApiController
func (c *BandwidthApiController) Routes() Routes {
	return Routes{ 
		{
			"GetCustomBandwidth",
			strings.ToUpper("Post"),
			"/nac/v2/subscriber/bandwidth/custom",
			c.GetCustomBandwidth,
		},
		{
			"GetSubscriberBandwidth",
			strings.ToUpper("Post"),
			"/nac/v2/subscriber/bandwidth",
			c.GetSubscriberBandwidth,
		},
		{
			"UpdateCustomBandwidth",
			strings.ToUpper("Patch"),
			"/nac/v2/subscriber/bandwidth/custom",
			c.UpdateCustomBandwidth,
		},
		{
			"UpdateSubscriberBandwidth",
			strings.ToUpper("Patch"),
			"/nac/v2/subscriber/bandwidth",
			c.UpdateSubscriberBandwidth,
		},
	}
}

// GetCustomBandwidth - Get upload/download limit
func (c *BandwidthApiController) GetCustomBandwidth(w http.ResponseWriter, r *http.Request) {
	subscriberIdParam := SubscriberId{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&subscriberIdParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertSubscriberIdRequired(subscriberIdParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	xTestmodeParam := r.Header.Get("x-testmode")
	result, err := c.service.GetCustomBandwidth(r.Context(), subscriberIdParam, xTestmodeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetSubscriberBandwidth - Get the current subscriber bandwidth
func (c *BandwidthApiController) GetSubscriberBandwidth(w http.ResponseWriter, r *http.Request) {
	subscriberIdParam := SubscriberId{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&subscriberIdParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertSubscriberIdRequired(subscriberIdParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	xTestmodeParam := r.Header.Get("x-testmode")
	result, err := c.service.GetSubscriberBandwidth(r.Context(), subscriberIdParam, xTestmodeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// UpdateCustomBandwidth - Set upload limit
func (c *BandwidthApiController) UpdateCustomBandwidth(w http.ResponseWriter, r *http.Request) {
	customLimitsParam := CustomLimits{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&customLimitsParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCustomLimitsRequired(customLimitsParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	xTestmodeParam := r.Header.Get("x-testmode")
	result, err := c.service.UpdateCustomBandwidth(r.Context(), customLimitsParam, xTestmodeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// UpdateSubscriberBandwidth - Update the bandwidth of the subscriber
func (c *BandwidthApiController) UpdateSubscriberBandwidth(w http.ResponseWriter, r *http.Request) {
	bandwidthUpdateParam := BandwidthUpdate{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bandwidthUpdateParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBandwidthUpdateRequired(bandwidthUpdateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	xTestmodeParam := r.Header.Get("x-testmode")
	result, err := c.service.UpdateSubscriberBandwidth(r.Context(), bandwidthUpdateParam, xTestmodeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
