/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"context"
	"net/http"
	"errors"
)

// SubscriberApiService is a service that implements the logic for the SubscriberApiServicer
// This service should implement the business logic for every endpoint for the SubscriberApi API.
// Include any external packages or services that will be required by this service.
type SubscriberApiService struct {
}

// NewSubscriberApiService creates a default api service
func NewSubscriberApiService() SubscriberApiServicer {
	return &SubscriberApiService{}
}

// CreateTestUser - Create a new test user
func (s *SubscriberApiService) CreateTestUser(ctx context.Context, subscriberDetails SubscriberDetails, xTestmode string) (ImplResponse, error) {
	// TODO - update CreateTestUser with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, SubscriberDetails{}) or use other options such as http.Ok ...
	//return Response(201, SubscriberDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTestUser method not implemented")
}

// DeleteTestuser - Delete an existing test user
func (s *SubscriberApiService) DeleteTestuser(ctx context.Context, subscriberId SubscriberId, xTestmode string) (ImplResponse, error) {
	// TODO - update DeleteTestuser with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteTestuser method not implemented")
}

// GetCustomBandwidth - Get upload/download limit
func (s *SubscriberApiService) GetCustomBandwidth(ctx context.Context, subscriberId SubscriberId, xTestmode string) (ImplResponse, error) {
	// TODO - update GetCustomBandwidth with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CustomLimits{}) or use other options such as http.Ok ...
	//return Response(200, CustomLimits{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCustomBandwidth method not implemented")
}

// GetSubscriber - Get the subscriber SUPI/IMSI and MSISDN
func (s *SubscriberApiService) GetSubscriber(ctx context.Context, subscriberId SubscriberId, xTestmode string) (ImplResponse, error) {
	// TODO - update GetSubscriber with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SubscriberDetails{}) or use other options such as http.Ok ...
	//return Response(200, SubscriberDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSubscriber method not implemented")
}

// GetSubscriberBandwidth - Get the current subscriber bandwidth
func (s *SubscriberApiService) GetSubscriberBandwidth(ctx context.Context, subscriberId SubscriberId, xTestmode string) (ImplResponse, error) {
	// TODO - update GetSubscriberBandwidth with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, BandwidthResponse{}) or use other options such as http.Ok ...
	//return Response(200, BandwidthResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSubscriberBandwidth method not implemented")
}

// GetSubscriberLocation - Get last reported location
func (s *SubscriberApiService) GetSubscriberLocation(ctx context.Context, subscriberId SubscriberId, xTestmode string) (ImplResponse, error) {
	// TODO - update GetSubscriberLocation with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, LocationResponse{}) or use other options such as http.Ok ...
	//return Response(200, LocationResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSubscriberLocation method not implemented")
}

// UpdateCustomBandwidth - Set upload limit
func (s *SubscriberApiService) UpdateCustomBandwidth(ctx context.Context, customLimits CustomLimits, xTestmode string) (ImplResponse, error) {
	// TODO - update UpdateCustomBandwidth with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CustomLimits{}) or use other options such as http.Ok ...
	//return Response(200, CustomLimits{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateCustomBandwidth method not implemented")
}

// UpdateSubscriberBandwidth - Update the bandwidth of the subscriber
func (s *SubscriberApiService) UpdateSubscriberBandwidth(ctx context.Context, bandwidthUpdate BandwidthUpdate, xTestmode string) (ImplResponse, error) {
	// TODO - update UpdateSubscriberBandwidth with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, BandwidthResponse{}) or use other options such as http.Ok ...
	//return Response(200, BandwidthResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, ApiError{}) or use other options such as http.Ok ...
	//return Response(400, ApiError{}), nil

	//TODO: Uncomment the next line to return response Response(0, ApiError{}) or use other options such as http.Ok ...
	//return Response(0, ApiError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateSubscriberBandwidth method not implemented")
}
