/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

type ApiError struct {

	Error string `json:"error,omitempty"`
}

// AssertApiErrorRequired checks if the required fields are not zero-ed
func AssertApiErrorRequired(obj ApiError) error {
	return nil
}

// AssertRecurseApiErrorRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ApiError (e.g. [][]ApiError), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseApiErrorRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApiError, ok := obj.(ApiError)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertApiErrorRequired(aApiError)
	})
}
