/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

type SubscriberDetails struct {

	Id string `json:"id,omitempty"`

	Imsi string `json:"imsi,omitempty"`

	Msisdn string `json:"msisdn,omitempty"`
}

// AssertSubscriberDetailsRequired checks if the required fields are not zero-ed
func AssertSubscriberDetailsRequired(obj SubscriberDetails) error {
	return nil
}

// AssertRecurseSubscriberDetailsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SubscriberDetails (e.g. [][]SubscriberDetails), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSubscriberDetailsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSubscriberDetails, ok := obj.(SubscriberDetails)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSubscriberDetailsRequired(aSubscriberDetails)
	})
}
