/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

type HelloResponses struct {

	Service string `json:"service,omitempty"`
}

// AssertHelloResponsesRequired checks if the required fields are not zero-ed
func AssertHelloResponsesRequired(obj HelloResponses) error {
	return nil
}

// AssertRecurseHelloResponsesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HelloResponses (e.g. [][]HelloResponses), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHelloResponsesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHelloResponses, ok := obj.(HelloResponses)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHelloResponsesRequired(aHelloResponses)
	})
}
