/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

type CustomLimits struct {

	Id string `json:"id,omitempty"`

	// Upload limit in bits per second
	Upload int32 `json:"upload,omitempty"`

	// Download limit in bits per second
	Download int32 `json:"download,omitempty"`
}

// AssertCustomLimitsRequired checks if the required fields are not zero-ed
func AssertCustomLimitsRequired(obj CustomLimits) error {
	return nil
}

// AssertRecurseCustomLimitsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CustomLimits (e.g. [][]CustomLimits), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCustomLimitsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCustomLimits, ok := obj.(CustomLimits)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCustomLimitsRequired(aCustomLimits)
	})
}
