/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

type SubscriberId struct {

	Id string `json:"id"`
}

// AssertSubscriberIdRequired checks if the required fields are not zero-ed
func AssertSubscriberIdRequired(obj SubscriberId) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSubscriberIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SubscriberId (e.g. [][]SubscriberId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSubscriberIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSubscriberId, ok := obj.(SubscriberId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSubscriberIdRequired(aSubscriberId)
	})
}
