/*
 * Network as Code
 *
 * Manipulate network conditions via simplified REST calls
 *
 * API version: 2
 * Contact: todd.levi@nokia.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

type BandwidthUpdate struct {

	Id string `json:"id,omitempty"`

	Bandwidth Bandwidth `json:"bandwidth,omitempty"`
}

// AssertBandwidthUpdateRequired checks if the required fields are not zero-ed
func AssertBandwidthUpdateRequired(obj BandwidthUpdate) error {
	return nil
}

// AssertRecurseBandwidthUpdateRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BandwidthUpdate (e.g. [][]BandwidthUpdate), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBandwidthUpdateRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBandwidthUpdate, ok := obj.(BandwidthUpdate)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBandwidthUpdateRequired(aBandwidthUpdate)
	})
}
